language: php

matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
      env:
        - ENABLE_XDEBUG=true
    - php: 7.1
      env:
        - ENABLE_DEVTOOLS=true
    - php: nightly
  allow_failures:
    - php: nightly
  fast_finish: true

os:
  - linux

notifications:
  irc: "chat.freenode.net#igororaproject"

sudo: false

env:
  global:
    - secure: "AAAAB3NzaC1yc2EAAAADAQABAAAAgQCOn1RsnFs5AvK4d2MZdh+mDPQu81nGxJCSmI5pSwRSOR4GfOYPoZc6vghxpE3+3d0XljxGfbwySgVnNSmGXX/FatJAIMMd6WgcebkgO89Q8XOFeFvO7uQ11I4DwhxgAAdR2NQOr0ovbrSsFPBN9DhJypPgYJwXg/thCuW569rWTw=="

cache:
  directories:
    - vendor/

before_script:
  - export PATH="$PATH:$HOME/.composer/vendor/bin"
  - if [[ ! $ENABLE_XDEBUG ]]; then
      phpenv config-rm xdebug.ini || echo "ext-xdebug is not available, cannot remove it.";
    fi

script:
  - composer install
  - vendor/bin/igorora test:run
  - if [[ $ENABLE_DEVTOOLS ]]; then
      composer global require friendsofphp/php-cs-fixer;
      vendor/bin/igorora devtools:cs --diff --dry-run .;
    fi
